/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 12-11-2008
 * 
 * XDoclet definition:
 * @struts.form name="CourseMasterForm"
 */
public class CourseMasterForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** coursecontent property */
	private String coursecontent;

	/** courseDesc property */
	private String courseDesc;

	/** courseName property */
	private String courseName;

	/** noOfLecturers property */
	private int noOfLecturers;

	/** courseDuration property */
	private String courseDuration;

	/** courseId property */
	private int courseId;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the coursecontent.
	 * @return String
	 */
	public String getCoursecontent() {
		return coursecontent;
	}

	/** 
	 * Set the coursecontent.
	 * @param coursecontent The coursecontent to set
	 */
	public void setCoursecontent(String coursecontent) {
		this.coursecontent = coursecontent;
	}

	/** 
	 * Returns the courseDesc.
	 * @return String
	 */
	public String getCourseDesc() {
		return courseDesc;
	}

	/** 
	 * Set the courseDesc.
	 * @param courseDesc The courseDesc to set
	 */
	public void setCourseDesc(String courseDesc) {
		this.courseDesc = courseDesc;
	}

	/** 
	 * Returns the courseName.
	 * @return String
	 */
	public String getCourseName() {
		return courseName;
	}

	/** 
	 * Set the courseName.
	 * @param courseName The courseName to set
	 */
	public void setCourseName(String courseName) {
		this.courseName = courseName;
	}

	/** 
	 * Returns the noOfLecturers.
	 * @return int
	 */
	public int getNoOfLecturers() {
		return noOfLecturers;
	}

	/** 
	 * Set the noOfLecturers.
	 * @param noOfLecturers The noOfLecturers to set
	 */
	public void setNoOfLecturers(int noOfLecturers) {
		this.noOfLecturers = noOfLecturers;
	}

	/** 
	 * Returns the courseDuration.
	 * @return String
	 */
	public String getCourseDuration() {
		return courseDuration;
	}

	/** 
	 * Set the courseDuration.
	 * @param courseDuration The courseDuration to set
	 */
	public void setCourseDuration(String courseDuration) {
		this.courseDuration = courseDuration;
	}

	/** 
	 * Returns the courseId.
	 * @return int
	 */
	public int getCourseId() {
		return courseId;
	}

	/** 
	 * Set the courseId.
	 * @param courseId The courseId to set
	 */
	public void setCourseId(int courseId) {
		this.courseId = courseId;
	}
}