/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 12-11-2008
 * 
 * XDoclet definition:
 * @struts.form name="courseLecturerMasterForm"
 */
public class CourseLecturerMasterForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** lecturerVideo property */
	private String lecturerVideo;
private String cname;
private String fname;
	/** facultyId property */
	private int facultyId;

	/** lectureassignmentFile property */
	private String lectureassignmentFile;

	/** lecturerDate property */
	private String lecturerDate;

	/** lectureDocumentfile property */
	private String lectureDocumentfile;

	/** lecturerPowerPoint property */
	private String lecturerPowerPoint;

	/** lecturerAudio property */
	private String lecturerAudio;

	/** lectureDurationTime property */
	private int lectureDurationTime;

	/** courseId property */
	private int courseId;

	/** lecturerId property */
	private int lecturerId;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the lecturerVideo.
	 * @return String
	 */
	public String getLecturerVideo() {
		return lecturerVideo;
	}

	/** 
	 * Set the lecturerVideo.
	 * @param lecturerVideo The lecturerVideo to set
	 */
	public void setLecturerVideo(String lecturerVideo) {
		this.lecturerVideo = lecturerVideo;
	}

	/** 
	 * Returns the facultyId.
	 * @return int
	 */
	public int getFacultyId() {
		return facultyId;
	}

	/** 
	 * Set the facultyId.
	 * @param facultyId The facultyId to set
	 */
	public void setFacultyId(int facultyId) {
		this.facultyId = facultyId;
	}

	/** 
	 * Returns the lectureassignmentFile.
	 * @return String
	 */
	public String getLectureassignmentFile() {
		return lectureassignmentFile;
	}

	/** 
	 * Set the lectureassignmentFile.
	 * @param lectureassignmentFile The lectureassignmentFile to set
	 */
	public void setLectureassignmentFile(String lectureassignmentFile) {
		this.lectureassignmentFile = lectureassignmentFile;
	}

	/** 
	 * Returns the lecturerDate.
	 * @return String
	 */
	public String getLecturerDate() {
		return lecturerDate;
	}

	/** 
	 * Set the lecturerDate.
	 * @param lecturerDate The lecturerDate to set
	 */
	public void setLecturerDate(String lecturerDate) {
		this.lecturerDate = lecturerDate;
	}

	/** 
	 * Returns the lectureDocumentfile.
	 * @return String
	 */
	public String getLectureDocumentfile() {
		return lectureDocumentfile;
	}

	/** 
	 * Set the lectureDocumentfile.
	 * @param lectureDocumentfile The lectureDocumentfile to set
	 */
	public void setLectureDocumentfile(String lectureDocumentfile) {
		this.lectureDocumentfile = lectureDocumentfile;
	}

	/** 
	 * Returns the lecturerPowerPoint.
	 * @return String
	 */
	public String getLecturerPowerPoint() {
		return lecturerPowerPoint;
	}

	/** 
	 * Set the lecturerPowerPoint.
	 * @param lecturerPowerPoint The lecturerPowerPoint to set
	 */
	public void setLecturerPowerPoint(String lecturerPowerPoint) {
		this.lecturerPowerPoint = lecturerPowerPoint;
	}

	/** 
	 * Returns the lecturerAudio.
	 * @return String
	 */
	public String getLecturerAudio() {
		return lecturerAudio;
	}

	/** 
	 * Set the lecturerAudio.
	 * @param lecturerAudio The lecturerAudio to set
	 */
	public void setLecturerAudio(String lecturerAudio) {
		this.lecturerAudio = lecturerAudio;
	}

	/** 
	 * Returns the lectureDurationTime.
	 * @return String
	 */
	public int getLectureDurationTime() {
		return lectureDurationTime;
	}

	/** 
	 * Set the lectureDurationTime.
	 * @param lectureDurationTime The lectureDurationTime to set
	 */
	public void setLectureDurationTime(int lectureDurationTime) {
		this.lectureDurationTime = lectureDurationTime;
	}

	/** 
	 * Returns the courseId.
	 * @return int
	 */
	public int getCourseId() {
		return courseId;
	}

	/** 
	 * Set the courseId.
	 * @param courseId The courseId to set
	 */
	public void setCourseId(int courseId) {
		this.courseId = courseId;
	}

	/** 
	 * Returns the lecturerId.
	 * @return int
	 */
	public int getLecturerId() {
		return lecturerId;
	}

	/** 
	 * Set the lecturerId.
	 * @param lecturerId The lecturerId to set
	 */
	public void setLecturerId(int lecturerId) {
		this.lecturerId = lecturerId;
	}

	public String getCname() {
		return cname;
	}

	public void setCname(String cname) {
		this.cname = cname;
	}

	public String getFname() {
		return fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}
}