/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 01-22-2009
 * 
 * XDoclet definition:
 * @struts.form name="customerTransactionMasterForm"
 */
public class CustomerTransactionMasterForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** transactionTime property */
	private String transactionTime;

	/** branchName property */
	private String branchName;

	/** transactionDate property */
	private String transactionDate;

	/** dateOfChqOrDd property */
	private String dateOfChqOrDd;

	/** transactionVoucerType property */
	private String transactionVoucerType;

	/** customerId property */
	private int customerId;

	/** chqOrDdNo property */
	private String chqOrDdNo;

	/** amount property */
	private int amount;

	/** accountNo property */
	private String accountNo;

	/** transactionType property */
	private String transactionType;

	/** balanceAdjusted property */
	private int balanceAdjusted;

	/** transactionConfirmDate property */
	private String transactionConfirmDate;

	/** employeId property */
	private int employeId;

	/** customerTransactionId property */
	private int customerTransactionId;

	/** transactionConfirmState property */
	private String transactionConfirmState;

	/** bankName property */
	private String bankName;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the transactionTime.
	 * @return String
	 */
	public String getTransactionTime() {
		return transactionTime;
	}

	/** 
	 * Set the transactionTime.
	 * @param transactionTime The transactionTime to set
	 */
	public void setTransactionTime(String transactionTime) {
		this.transactionTime = transactionTime;
	}

	/** 
	 * Returns the branchName.
	 * @return String
	 */
	public String getBranchName() {
		return branchName;
	}

	/** 
	 * Set the branchName.
	 * @param branchName The branchName to set
	 */
	public void setBranchName(String branchName) {
		this.branchName = branchName;
	}

	/** 
	 * Returns the transactionDate.
	 * @return String
	 */
	public String getTransactionDate() {
		return transactionDate;
	}

	/** 
	 * Set the transactionDate.
	 * @param transactionDate The transactionDate to set
	 */
	public void setTransactionDate(String transactionDate) {
		this.transactionDate = transactionDate;
	}

	/** 
	 * Returns the dateOfChqOrDd.
	 * @return String
	 */
	public String getDateOfChqOrDd() {
		return dateOfChqOrDd;
	}

	/** 
	 * Set the dateOfChqOrDd.
	 * @param dateOfChqOrDd The dateOfChqOrDd to set
	 */
	public void setDateOfChqOrDd(String dateOfChqOrDd) {
		this.dateOfChqOrDd = dateOfChqOrDd;
	}

	/** 
	 * Returns the transactionVoucerType.
	 * @return String
	 */
	public String getTransactionVoucerType() {
		return transactionVoucerType;
	}

	/** 
	 * Set the transactionVoucerType.
	 * @param transactionVoucerType The transactionVoucerType to set
	 */
	public void setTransactionVoucerType(String transactionVoucerType) {
		this.transactionVoucerType = transactionVoucerType;
	}

	/** 
	 * Returns the customerId.
	 * @return int
	 */
	public int getCustomerId() {
		return customerId;
	}

	/** 
	 * Set the customerId.
	 * @param customerId The customerId to set
	 */
	public void setCustomerId(int customerId) {
		this.customerId = customerId;
	}

	/** 
	 * Returns the chqOrDdNo.
	 * @return String
	 */
	public String getChqOrDdNo() {
		return chqOrDdNo;
	}

	/** 
	 * Set the chqOrDdNo.
	 * @param chqOrDdNo The chqOrDdNo to set
	 */
	public void setChqOrDdNo(String chqOrDdNo) {
		this.chqOrDdNo = chqOrDdNo;
	}

	/** 
	 * Returns the amount.
	 * @return int
	 */
	public int getAmount() {
		return amount;
	}

	/** 
	 * Set the amount.
	 * @param amount The amount to set
	 */
	public void setAmount(int amount) {
		this.amount = amount;
	}

	/** 
	 * Returns the accountNo.
	 * @return String
	 */
	public String getAccountNo() {
		return accountNo;
	}

	/** 
	 * Set the accountNo.
	 * @param accountNo The accountNo to set
	 */
	public void setAccountNo(String accountNo) {
		this.accountNo = accountNo;
	}

	/** 
	 * Returns the transactionType.
	 * @return String
	 */
	public String getTransactionType() {
		return transactionType;
	}

	/** 
	 * Set the transactionType.
	 * @param transactionType The transactionType to set
	 */
	public void setTransactionType(String transactionType) {
		this.transactionType = transactionType;
	}

	/** 
	 * Returns the balanceAdjusted.
	 * @return int
	 */
	public int getBalanceAdjusted() {
		return balanceAdjusted;
	}

	/** 
	 * Set the balanceAdjusted.
	 * @param balanceAdjusted The balanceAdjusted to set
	 */
	public void setBalanceAdjusted(int balanceAdjusted) {
		this.balanceAdjusted = balanceAdjusted;
	}

	/** 
	 * Returns the transactionConfirmDate.
	 * @return String
	 */
	public String getTransactionConfirmDate() {
		return transactionConfirmDate;
	}

	/** 
	 * Set the transactionConfirmDate.
	 * @param transactionConfirmDate The transactionConfirmDate to set
	 */
	public void setTransactionConfirmDate(String transactionConfirmDate) {
		this.transactionConfirmDate = transactionConfirmDate;
	}

	/** 
	 * Returns the employeId.
	 * @return int
	 */
	public int getEmployeId() {
		return employeId;
	}

	/** 
	 * Set the employeId.
	 * @param employeId The employeId to set
	 */
	public void setEmployeId(int employeId) {
		this.employeId = employeId;
	}

	/** 
	 * Returns the customerTransactionId.
	 * @return int
	 */
	public int getCustomerTransactionId() {
		return customerTransactionId;
	}

	/** 
	 * Set the customerTransactionId.
	 * @param customerTransactionId The customerTransactionId to set
	 */
	public void setCustomerTransactionId(int customerTransactionId) {
		this.customerTransactionId = customerTransactionId;
	}

	/** 
	 * Returns the transactionConfirmState.
	 * @return String
	 */
	public String getTransactionConfirmState() {
		return transactionConfirmState;
	}

	/** 
	 * Set the transactionConfirmState.
	 * @param transactionConfirmState The transactionConfirmState to set
	 */
	public void setTransactionConfirmState(String transactionConfirmState) {
		this.transactionConfirmState = transactionConfirmState;
	}

	/** 
	 * Returns the bankName.
	 * @return String
	 */
	public String getBankName() {
		return bankName;
	}

	/** 
	 * Set the bankName.
	 * @param bankName The bankName to set
	 */
	public void setBankName(String bankName) {
		this.bankName = bankName;
	}
}