/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 12-11-2008
 * 
 * XDoclet definition:
 * @struts.form name="emailDetailsForm"
 */
public class EmailDetailsForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** fromstudentId property */
	private int fromstudentId;

	/** toStudentId property */
	private int toStudentId;

	/** fromFacultyId property */
	private int fromFacultyId;

	/** toFacultyId property */
	private int toFacultyId;

	/** emailId property */
	private int emailId;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the fromstudentId.
	 * @return int
	 */
	public int getFromstudentId() {
		return fromstudentId;
	}

	/** 
	 * Set the fromstudentId.
	 * @param fromstudentId The fromstudentId to set
	 */
	public void setFromstudentId(int fromstudentId) {
		this.fromstudentId = fromstudentId;
	}

	/** 
	 * Returns the toStudentId.
	 * @return int
	 */
	public int getToStudentId() {
		return toStudentId;
	}

	/** 
	 * Set the toStudentId.
	 * @param toStudentId The toStudentId to set
	 */
	public void setToStudentId(int toStudentId) {
		this.toStudentId = toStudentId;
	}

	/** 
	 * Returns the fromFacultyId.
	 * @return int
	 */
	public int getFromFacultyId() {
		return fromFacultyId;
	}

	/** 
	 * Set the fromFacultyId.
	 * @param fromFacultyId The fromFacultyId to set
	 */
	public void setFromFacultyId(int fromFacultyId) {
		this.fromFacultyId = fromFacultyId;
	}

	/** 
	 * Returns the toFacultyId.
	 * @return int
	 */
	public int getToFacultyId() {
		return toFacultyId;
	}

	/** 
	 * Set the toFacultyId.
	 * @param toFacultyId The toFacultyId to set
	 */
	public void setToFacultyId(int toFacultyId) {
		this.toFacultyId = toFacultyId;
	}

	/** 
	 * Returns the emailId.
	 * @return int
	 */
	public int getEmailId() {
		return emailId;
	}

	/** 
	 * Set the emailId.
	 * @param emailId The emailId to set
	 */
	public void setEmailId(int emailId) {
		this.emailId = emailId;
	}
}