/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 12-11-2008
 * 
 * XDoclet definition:
 * @struts.form name="examQuestionMasterForm"
 */
public class ExamQuestionMasterForm extends ActionForm {
	/*
	 * Generated fields
	 */
private int studentexamid;
	/** questionText property */
	private String questionText;

	/** answer5 property */
	private String answer5;
private String examDate;
	/** answer1 property */
	private String answer1;

	/** marks property */
	private int marks;

	/** answer3 property */
	private String answer3;

	/** examinationId property */
	private int examinationId;

	/** questionId property */
	private int questionId;

	/** answer4 property */
	private String answer4;

	/** correctAnswer property */
	private String correctAnswer;

	/** answer2 property */
	private String answer2;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the questionText.
	 * @return String
	 */
	public String getQuestionText() {
		return questionText;
	}

	/** 
	 * Set the questionText.
	 * @param questionText The questionText to set
	 */
	public void setQuestionText(String questionText) {
		this.questionText = questionText;
	}

	/** 
	 * Returns the answer5.
	 * @return String
	 */
	public String getAnswer5() {
		return answer5;
	}

	/** 
	 * Set the answer5.
	 * @param answer5 The answer5 to set
	 */
	public void setAnswer5(String answer5) {
		this.answer5 = answer5;
	}

	/** 
	 * Returns the answer1.
	 * @return String
	 */
	public String getAnswer1() {
		return answer1;
	}

	/** 
	 * Set the answer1.
	 * @param answer1 The answer1 to set
	 */
	public void setAnswer1(String answer1) {
		this.answer1 = answer1;
	}

	/** 
	 * Returns the marks.
	 * @return int
	 */
	public int getMarks() {
		return marks;
	}

	/** 
	 * Set the marks.
	 * @param marks The marks to set
	 */
	public void setMarks(int marks) {
		this.marks = marks;
	}

	/** 
	 * Returns the answer3.
	 * @return String
	 */
	public String getAnswer3() {
		return answer3;
	}

	/** 
	 * Set the answer3.
	 * @param answer3 The answer3 to set
	 */
	public void setAnswer3(String answer3) {
		this.answer3 = answer3;
	}

	/** 
	 * Returns the examinationId.
	 * @return int
	 */
	public int getExaminationId() {
		return examinationId;
	}

	/** 
	 * Set the examinationId.
	 * @param examinationId The examinationId to set
	 */
	public void setExaminationId(int examinationId) {
		this.examinationId = examinationId;
	}

	/** 
	 * Returns the questionId.
	 * @return int
	 */
	public int getQuestionId() {
		return questionId;
	}

	/** 
	 * Set the questionId.
	 * @param questionId The questionId to set
	 */
	public void setQuestionId(int questionId) {
		this.questionId = questionId;
	}

	/** 
	 * Returns the answer4.
	 * @return String
	 */
	public String getAnswer4() {
		return answer4;
	}

	/** 
	 * Set the answer4.
	 * @param answer4 The answer4 to set
	 */
	public void setAnswer4(String answer4) {
		this.answer4 = answer4;
	}

	/** 
	 * Returns the correctAnswer.
	 * @return String
	 */
	public String getCorrectAnswer() {
		return correctAnswer;
	}

	/** 
	 * Set the correctAnswer.
	 * @param correctAnswer The correctAnswer to set
	 */
	public void setCorrectAnswer(String correctAnswer) {
		this.correctAnswer = correctAnswer;
	}

	/** 
	 * Returns the answer2.
	 * @return String
	 */
	public String getAnswer2() {
		return answer2;
	}

	/** 
	 * Set the answer2.
	 * @param answer2 The answer2 to set
	 */
	public void setAnswer2(String answer2) {
		this.answer2 = answer2;
	}

	public String getExamDate() {
		return examDate;
	}

	public void setExamDate(String examDate) {
		this.examDate = examDate;
	}

	public int getStudentexamid() {
		return studentexamid;
	}

	public void setStudentexamid(int studentexamid) {
		this.studentexamid = studentexamid;
	}
}