/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 12-11-2008
 * 
 * XDoclet definition:
 * @struts.form name="examinationScheduleForm"
 */
public class ExaminationScheduleForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** facultyId property */
	private int facultyId;
private String examname;
private int noofquestions;
	/** passPercentageDecided property */
	private int passPercentageDecided;

	/** examinationDate property */
	private String examinationDate;
private String lectureDate;
private String fname;
private String cname;
	/** courseId property */
	private int courseId;

	/** lecturerId property */
	private int lecturerId;

	/** examinationId property */
	private int examinationId;

	/** examinationEndDate property */
	private String examinationEndDate;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the facultyId.
	 * @return int
	 */
	public int getFacultyId() {
		return facultyId;
	}

	/** 
	 * Set the facultyId.
	 * @param facultyId The facultyId to set
	 */
	public void setFacultyId(int facultyId) {
		this.facultyId = facultyId;
	}

	/** 
	 * Returns the passPercentageDecided.
	 * @return int
	 */
	public int getPassPercentageDecided() {
		return passPercentageDecided;
	}

	/** 
	 * Set the passPercentageDecided.
	 * @param passPercentageDecided The passPercentageDecided to set
	 */
	public void setPassPercentageDecided(int passPercentageDecided) {
		this.passPercentageDecided = passPercentageDecided;
	}

	/** 
	 * Returns the examinationDate.
	 * @return String
	 */
	public String getExaminationDate() {
		return examinationDate;
	}

	/** 
	 * Set the examinationDate.
	 * @param examinationDate The examinationDate to set
	 */
	public void setExaminationDate(String examinationDate) {
		this.examinationDate = examinationDate;
	}

	/** 
	 * Returns the courseId.
	 * @return int
	 */
	public int getCourseId() {
		return courseId;
	}

	/** 
	 * Set the courseId.
	 * @param courseId The courseId to set
	 */
	public void setCourseId(int courseId) {
		this.courseId = courseId;
	}

	/** 
	 * Returns the lecturerId.
	 * @return int
	 */
	public int getLecturerId() {
		return lecturerId;
	}

	/** 
	 * Set the lecturerId.
	 * @param lecturerId The lecturerId to set
	 */
	public void setLecturerId(int lecturerId) {
		this.lecturerId = lecturerId;
	}

	/** 
	 * Returns the examinationId.
	 * @return int
	 */
	public int getExaminationId() {
		return examinationId;
	}

	/** 
	 * Set the examinationId.
	 * @param examinationId The examinationId to set
	 */
	public void setExaminationId(int examinationId) {
		this.examinationId = examinationId;
	}

	/** 
	 * Returns the examinationEndDate.
	 * @return String
	 */
	public String getExaminationEndDate() {
		return examinationEndDate;
	}

	/** 
	 * Set the examinationEndDate.
	 * @param examinationEndDate The examinationEndDate to set
	 */
	public void setExaminationEndDate(String examinationEndDate) {
		this.examinationEndDate = examinationEndDate;
	}

	public String getLectureDate() {
		return lectureDate;
	}

	public void setLectureDate(String lectureDate) {
		this.lectureDate = lectureDate;
	}

	public String getFname() {
		return fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

	public String getCname() {
		return cname;
	}

	public void setCname(String cname) {
		this.cname = cname;
	}

	public String getExamname() {
		return examname;
	}

	public void setExamname(String examname) {
		this.examname = examname;
	}

	public int getNoofquestions() {
		return noofquestions;
	}

	public void setNoofquestions(int noofquestions) {
		this.noofquestions = noofquestions;
	}
}