/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 12-11-2008
 * 
 * XDoclet definition:
 * @struts.form name="FacultyMasterForm"
 */
public class FacultyMasterForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** phone property */
	private String phone;
	private String username;
	
    private int courseId;
    private String password;
    private String descByDFaculty;
	/** facultyId property */
	private int facultyId;

	/** dor property */
	private String dor;

	/** facultyMiddleName property */
	private String facultyMiddleName;

	/** facultyfirstname property */
	private String facultyfirstname;

	/** address property */
	private String address;

	/** image property */
	private String image;

	/** dob property */
	private String dob;

	/** email property */
	private String email;

	/** facultyLastName property */
	private String facultyLastName;

	/** experience property */
	private int experience;

	/** specialRemarks property */
	private String specialRemarks;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the phone.
	 * @return String
	 */
	public String getPhone() {
		return phone;
	}

	/** 
	 * Set the phone.
	 * @param phone The phone to set
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/** 
	 * Returns the facultyId.
	 * @return int
	 */
	public int getFacultyId() {
		return facultyId;
	}

	/** 
	 * Set the facultyId.
	 * @param facultyId The facultyId to set
	 */
	public void setFacultyId(int facultyId) {
		this.facultyId = facultyId;
	}

	/** 
	 * Returns the dor.
	 * @return String
	 */
	public String getDor() {
		return dor;
	}

	/** 
	 * Set the dor.
	 * @param dor The dor to set
	 */
	public void setDor(String dor) {
		this.dor = dor;
	}

	/** 
	 * Returns the facultyMiddleName.
	 * @return String
	 */
	public String getFacultyMiddleName() {
		return facultyMiddleName;
	}

	/** 
	 * Set the facultyMiddleName.
	 * @param facultyMiddleName The facultyMiddleName to set
	 */
	public void setFacultyMiddleName(String facultyMiddleName) {
		this.facultyMiddleName = facultyMiddleName;
	}

	/** 
	 * Returns the facultyfirstname.
	 * @return String
	 */
	public String getFacultyfirstname() {
		return facultyfirstname;
	}

	/** 
	 * Set the facultyfirstname.
	 * @param facultyfirstname The facultyfirstname to set
	 */
	public void setFacultyfirstname(String facultyfirstname) {
		this.facultyfirstname = facultyfirstname;
	}

	/** 
	 * Returns the address.
	 * @return String
	 */
	public String getAddress() {
		return address;
	}

	/** 
	 * Set the address.
	 * @param address The address to set
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/** 
	 * Returns the image.
	 * @return String
	 */
	public String getImage() {
		return image;
	}

	/** 
	 * Set the image.
	 * @param image The image to set
	 */
	public void setImage(String image) {
		this.image = image;
	}

	/** 
	 * Returns the dob.
	 * @return String
	 */
	public String getDob() {
		return dob;
	}

	/** 
	 * Set the dob.
	 * @param dob The dob to set
	 */
	public void setDob(String dob) {
		this.dob = dob;
	}

	/** 
	 * Returns the email.
	 * @return String
	 */
	public String getEmail() {
		return email;
	}

	/** 
	 * Set the email.
	 * @param email The email to set
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/** 
	 * Returns the facultyLastName.
	 * @return String
	 */
	public String getFacultyLastName() {
		return facultyLastName;
	}

	/** 
	 * Set the facultyLastName.
	 * @param facultyLastName The facultyLastName to set
	 */
	public void setFacultyLastName(String facultyLastName) {
		this.facultyLastName = facultyLastName;
	}

	/** 
	 * Returns the experience.
	 * @return int
	 */
	public int getExperience() {
		return experience;
	}

	/** 
	 * Set the experience.
	 * @param experience The experience to set
	 */
	public void setExperience(int experience) {
		this.experience = experience;
	}

	/** 
	 * Returns the specialRemarks.
	 * @return String
	 */
	public String getSpecialRemarks() {
		return specialRemarks;
	}

	/** 
	 * Set the specialRemarks.
	 * @param specialRemarks The specialRemarks to set
	 */
	public void setSpecialRemarks(String specialRemarks) {
		this.specialRemarks = specialRemarks;
	}

	public int getCourseId() {
		return courseId;
	}

	public void setCourseId(int courseId) {
		this.courseId = courseId;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getDescByDFaculty() {
		return descByDFaculty;
	}

	public void setDescByDFaculty(String descByDFaculty) {
		this.descByDFaculty = descByDFaculty;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}
}