/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 12-11-2008
 * 
 * XDoclet definition:
 * @struts.form name="facultyOnlineMasterForm"
 */
public class FacultyOnlineMasterForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** facultyId property */
	private int facultyId;
private String Fname;
	/** onlineId property */
	private int onlineId;

	/** onlineDateTime property */
	private String onlineDateTime;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the facultyId.
	 * @return int
	 */
	public int getFacultyId() {
		return facultyId;
	}

	/** 
	 * Set the facultyId.
	 * @param facultyId The facultyId to set
	 */
	public void setFacultyId(int facultyId) {
		this.facultyId = facultyId;
	}

	/** 
	 * Returns the onlineId.
	 * @return int
	 */
	public int getOnlineId() {
		return onlineId;
	}

	/** 
	 * Set the onlineId.
	 * @param onlineId The onlineId to set
	 */
	public void setOnlineId(int onlineId) {
		this.onlineId = onlineId;
	}

	/** 
	 * Returns the onlineDateTime.
	 * @return String
	 */
	public String getOnlineDateTime() {
		return onlineDateTime;
	}

	/** 
	 * Set the onlineDateTime.
	 * @param onlineDateTime The onlineDateTime to set
	 */
	public void setOnlineDateTime(String onlineDateTime) {
		this.onlineDateTime = onlineDateTime;
	}

	public String getFname() {
		return Fname;
	}

	public void setFname(String fname) {
		Fname = fname;
	}
}