/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 12-11-2008
 * 
 * XDoclet definition:
 * @struts.form name="studentCourseMasterForm"
 */
public class StudentCourseMasterForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** facultyId property */
	private int facultyId;
private String sname;
private String cname;
private String fname;
	/** studentId property */
	private int studentId;

	/** courseEndDate property */
	private String courseEndDate;

	/** regDate property */
	private String regDate;

	/** courseId property */
	private int courseId;

	/** courseRegId property */
	private int courseRegId;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the facultyId.
	 * @return int
	 */
	public int getFacultyId() {
		return facultyId;
	}

	/** 
	 * Set the facultyId.
	 * @param facultyId The facultyId to set
	 */
	public void setFacultyId(int facultyId) {
		this.facultyId = facultyId;
	}

	/** 
	 * Returns the studentId.
	 * @return int
	 */
	public int getStudentId() {
		return studentId;
	}

	/** 
	 * Set the studentId.
	 * @param studentId The studentId to set
	 */
	public void setStudentId(int studentId) {
		this.studentId = studentId;
	}

	/** 
	 * Returns the courseEndDate.
	 * @return String
	 */
	public String getCourseEndDate() {
		return courseEndDate;
	}

	/** 
	 * Set the courseEndDate.
	 * @param courseEndDate The courseEndDate to set
	 */
	public void setCourseEndDate(String courseEndDate) {
		this.courseEndDate = courseEndDate;
	}

	/** 
	 * Returns the regDate.
	 * @return String
	 */
	public String getRegDate() {
		return regDate;
	}

	/** 
	 * Set the regDate.
	 * @param regDate The regDate to set
	 */
	public void setRegDate(String regDate) {
		this.regDate = regDate;
	}

	/** 
	 * Returns the courseId.
	 * @return int
	 */
	public int getCourseId() {
		return courseId;
	}

	/** 
	 * Set the courseId.
	 * @param courseId The courseId to set
	 */
	public void setCourseId(int courseId) {
		this.courseId = courseId;
	}

	/** 
	 * Returns the courseRegId.
	 * @return int
	 */
	public int getCourseRegId() {
		return courseRegId;
	}

	/** 
	 * Set the courseRegId.
	 * @param courseRegId The courseRegId to set
	 */
	public void setCourseRegId(int courseRegId) {
		this.courseRegId = courseRegId;
	}

	public String getSname() {
		return sname;
	}

	public void setSname(String sname) {
		this.sname = sname;
	}

	public String getCname() {
		return cname;
	}

	public void setCname(String cname) {
		this.cname = cname;
	}

	public String getFname() {
		return fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}
}