/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 12-11-2008
 * 
 * XDoclet definition:
 * @struts.form name="studentExaminationDetailsForm"
 */
public class StudentExaminationDetailsForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** correct_wrong property */
	private String correct_wrong;
private int studentexamiid;
	/** answer property */
	private String answer;

	/** studentExamId property */
	private int studentExamId;
private String examAttendedDateTime;
private String questionText;
	/** questionId property */
	private int questionId;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the correct_wrong.
	 * @return String
	 */
	public String getCorrect_wrong() {
		return correct_wrong;
	}

	/** 
	 * Set the correct_wrong.
	 * @param correct_wrong The correct_wrong to set
	 */
	public void setCorrect_wrong(String correct_wrong) {
		this.correct_wrong = correct_wrong;
	}

	/** 
	 * Returns the answer.
	 * @return String
	 */
	public String getAnswer() {
		return answer;
	}

	/** 
	 * Set the answer.
	 * @param answer The answer to set
	 */
	public void setAnswer(String answer) {
		this.answer = answer;
	}

	/** 
	 * Returns the studentExamId.
	 * @return int
	 */
	public int getStudentExamId() {
		return studentExamId;
	}

	/** 
	 * Set the studentExamId.
	 * @param studentExamId The studentExamId to set
	 */
	public void setStudentExamId(int studentExamId) {
		this.studentExamId = studentExamId;
	}

	/** 
	 * Returns the questionId.
	 * @return int
	 */
	public int getQuestionId() {
		return questionId;
	}

	/** 
	 * Set the questionId.
	 * @param questionId The questionId to set
	 */
	public void setQuestionId(int questionId) {
		this.questionId = questionId;
	}

	public String getExamAttendedDateTime() {
		return examAttendedDateTime;
	}

	public void setExamAttendedDateTime(String examAttendedDateTime) {
		this.examAttendedDateTime = examAttendedDateTime;
	}

	public String getQuestionText() {
		return questionText;
	}

	public void setQuestionText(String questionText) {
		this.questionText = questionText;
	}

	public int getStudentexamiid() {
		return studentexamiid;
	}

	public void setStudentexamiid(int studentexamiid) {
		this.studentexamiid = studentexamiid;
	}
}