/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 12-11-2008
 * 
 * XDoclet definition:
 * @struts.form name="studentOnlineForm"
 */
public class StudentOnlineForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** studentId property */
	private int studentId;
private String StudentName;
	/** onlineDateAndTime property */
	private String onlineDateAndTime;

	/** onlineId property */
	private int onlineId;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the studentId.
	 * @return int
	 */
	public int getStudentId() {
		return studentId;
	}

	/** 
	 * Set the studentId.
	 * @param studentId The studentId to set
	 */
	public void setStudentId(int studentId) {
		this.studentId = studentId;
	}

	/** 
	 * Returns the onlineDateAndTime.
	 * @return String
	 */
	public String getOnlineDateAndTime() {
		return onlineDateAndTime;
	}

	/** 
	 * Set the onlineDateAndTime.
	 * @param onlineDateAndTime The onlineDateAndTime to set
	 */
	public void setOnlineDateAndTime(String onlineDateAndTime) {
		this.onlineDateAndTime = onlineDateAndTime;
	}

	/** 
	 * Returns the onlineId.
	 * @return int
	 */
	public int getOnlineId() {
		return onlineId;
	}

	/** 
	 * Set the onlineId.
	 * @param onlineId The onlineId to set
	 */
	public void setOnlineId(int onlineId) {
		this.onlineId = onlineId;
	}

	public String getStudentName() {
		return StudentName;
	}

	public void setStudentName(String studentName) {
		StudentName = studentName;
	}
}