/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 12-11-2008
 * 
 * XDoclet definition:
 * @struts.form name="voiceMailBoxMasterForm"
 */
public class VoiceMailBoxMasterForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** studentId property */
	private int studentId;
private String StudentName;
	/** audioFile property */
	private String audioFile;

	/** voiceMailBoxText property */
	private String voiceMailBoxText;

	/** voiceMailBoxId property */
	private int voiceMailBoxId;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the studentId.
	 * @return int
	 */
	public int getStudentId() {
		return studentId;
	}

	/** 
	 * Set the studentId.
	 * @param studentId The studentId to set
	 */
	public void setStudentId(int studentId) {
		this.studentId = studentId;
	}

	/** 
	 * Returns the audioFile.
	 * @return String
	 */
	public String getAudioFile() {
		return audioFile;
	}

	/** 
	 * Set the audioFile.
	 * @param audioFile The audioFile to set
	 */
	public void setAudioFile(String audioFile) {
		this.audioFile = audioFile;
	}

	/** 
	 * Returns the voiceMailBoxText.
	 * @return String
	 */
	public String getVoiceMailBoxText() {
		return voiceMailBoxText;
	}

	/** 
	 * Set the voiceMailBoxText.
	 * @param voiceMailBoxText The voiceMailBoxText to set
	 */
	public void setVoiceMailBoxText(String voiceMailBoxText) {
		this.voiceMailBoxText = voiceMailBoxText;
	}

	/** 
	 * Returns the voiceMailBoxId.
	 * @return int
	 */
	public int getVoiceMailBoxId() {
		return voiceMailBoxId;
	}

	/** 
	 * Set the voiceMailBoxId.
	 * @param voiceMailBoxId The voiceMailBoxId to set
	 */
	public void setVoiceMailBoxId(int voiceMailBoxId) {
		this.voiceMailBoxId = voiceMailBoxId;
	}

	public String getStudentName() {
		return StudentName;
	}

	public void setStudentName(String studentName) {
		StudentName = studentName;
	}
}