/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.dts.project.action;

import javax.servlet.RequestDispatcher;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.dts.dae.dao.SecurityDAO;
import com.yourcompany.struts.form.ProfileForm;

/** 
 * MyEclipse Struts
 * Creation date: 01-30-2009
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="success" path="/ChangePassword.jsp"
 * @struts.action-forward name="failure" path="/ChangePassword.jsp"
 */
public class ChangeSPasswordAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
HttpSession session =request.getSession();
		
	  	//if(session.getAttribute("user")==null)
	     //  response.sendRedirect("LoginForm.jsp?status=Session Expired");
	 
	 String page="";
	 
	  	if(((String)session.getAttribute("role")).equals("student"))
	  	{
	  	     page="StudentHome.jsp";
	  	 }else{
	  	     page="adminhome.jsp"; 
	  	}
	  
	    	String target="Password Changed Failed";
	       		ProfileForm profileForm=new ProfileForm(); 
	             profileForm.setPassword(request.getParameter("oldpassword")); 
	             profileForm.setLoginid(request.getParameter("username")); 
	            profileForm.setNewpassword(request.getParameter("newpassword")); 
	             
	            boolean flag=new SecurityDAO().changePassword(profileForm); 
	             
	            if(flag) 
	            {
	                target=page+"?status=Password Changed Successfully";
	                return mapping.findForward("success");
	            }
	            else
	            {
	                target=page+"?status=Password Changed Failed"; 
	               return mapping.findForward("failure");
	            }
	}
}