/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.dts.project.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.dts.dae.dao.ProfileDAO;
import com.yourcompany.struts.form.ProfileForm;

/** 
 * MyEclipse Struts
 * Creation date: 01-29-2009
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="success" path="/Registerform.jsp"
 * @struts.action-forward name="failure" path="/Registerform.jsp"
 */
public class RegisterAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		ProfileForm profileForm=(ProfileForm)form;
		ProfileDAO profileDAO=new ProfileDAO();
		boolean flag=profileDAO.registration(profileForm);
		if(flag)
			return mapping.findForward("success");
		else 
		   return mapping.findForward("failure");
	}
}