/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.dts.project.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.dts.dae.dao.QueryDAO;
import com.dts.dae.model.Query;

/** 
 * MyEclipse Struts
 * Creation date: 12-24-2008
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class SendQuery extends Action {
	
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		try{
			System.out.println();
		
			String desc=request.getParameter("description");
			String to=request.getParameter("to");
			String from=request.getParameter("customerID");
			System.out.println("from="+from);
			System.out.println("to="+to);
			System.out.println("desc="+desc);
			
		
			new QueryDAO().sendQuery(from,desc);
		
		}catch (Exception e) {
			// TODO: handle exception
		}return mapping.findForward("viewQueriesStatus");
	}
}