/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.dts.project.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.dts.project.dao.StudentCourseMasterDao;
import com.yourcompany.struts.form.StudentCourseMasterForm;

/** 
 * MyEclipse Struts
 * Creation date: 01-28-2009
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="success" path="/StudentCourseMaster.jsp"
 * @struts.action-forward name="failure" path="/StudentCourseMaster.jsp"
 */
public class StudentCourseAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		StudentCourseMasterForm studentCourseMasterForm=(StudentCourseMasterForm)form;
		StudentCourseMasterDao studentCourseMasterDao=new StudentCourseMasterDao();
		boolean flag=studentCourseMasterDao.insertStudentCourseMaster(studentCourseMasterForm);
		if(flag)
			return mapping.findForward("success");
		else
			return mapping.findForward("failure");
	}
}